### PR TITLE
fix: add custom validate

### LINKED ISSUE #75: permissions configuration missing
Hello, You mention the permissions and state that they are in the configuration.md doc, but there are no permissions there.

### PR DESCRIPTION
**Pull request by MyuddinKhatri**
closes #75 

Added custom_validate which is copy of `super().validate()` but it does not run `validate_file_on_disk` as in our case, file won't exist on disk.

### CODE REVIEW

**Comment by Alchez** [comment]
@MyuddinKhatri Can you also test what happens if cloud_storage is installed but the S3 credentials aren't configured?

**Comment by MyuddinKhatri** [comment]
> @MyuddinKhatri Can you also test what happens if cloud_storage is installed but the S3 credentials aren't configured?

@Alchez If cloud_storage is installed and S3 credentials aren't configured then the file is stored traditionally on the disk, inside `sites/`

**Comment by Alchez** [comment]
> @Alchez If cloud_storage is installed and S3 credentials aren't configured then the file is stored traditionally on the disk, inside `sites/`

@MyuddinKhatri Does the `validate_file_on_disk` function need to run in that case? I'm wondering if we should keep that function in our custom class but behind a flag maybe?

**Comment by agritheory** [comment]
Yes, we would want a flag. The preview features of Cloud Storage may be used as a dependency for other applications

**Comment by MyuddinKhatri** [comment]
> > @Alchez If cloud_storage is installed and S3 credentials aren't configured then the file is stored traditionally on the disk, inside `sites/`
> 
> 
> 
> @MyuddinKhatri Does the `validate_file_on_disk` function need to run in that case? I'm wondering if we should keep that function in our custom class but behind a flag maybe?

Yes, we should add a flag, and if the S3 credentials are not configured then run the 'validate_file_on_disk'

**Review by Alchez — APPROVED** [review]

**Pull request merged**
