### PR TITLE
ci: migrate to Python semantic release

### LINKED ISSUE #38: Migrate to python-semantic-release
https://python-semantic-release.readthedocs.io/en/latest/

### PR DESCRIPTION
**Pull request by HKuz**
Addresses #38 

Migrates repo to Python Semantic Release.

### CODE REVIEW

**Comment by HKuz** [comment]
Updated with the database logging changes so the testing step passes. The linter step is still failing - it says there are undetermined types in the `file.py` script.

**Comment by agritheory** [comment]
@HKuz You want to try adding the type annotations? Or if they should be ignored because they're Frappe types that aren't defined, that's OK too.

**Comment by HKuz** [comment]
@agritheory sure, I'll look into this. Looks like most of the errors are from undetermined type of frappe file object attributes, but there was one in the list was an incompatible argument type.

**Review by agritheory — APPROVED** [review]
Added types. Test failure is unrelated

**Pull request merged**
